t1_hello: t1_hello.c
	gcc -Wall -o $@ $<
	
t1_hello_fail: t1_hello_fail.c
	gcc -Wall -o $@ $<

t1_hello_annot: t1_hello_annot.c
	gcc -Wall -o $@ $<

t1_tipos_variaveis: t1_tipos_variaveis.c
	gcc -Wall -o $@ $<

t1_tamanhos_tipos: t1_tamanhos_tipos.c
	gcc -Wall -o $@ $<

t1_operadores_int: t1_operadores_int.c
	gcc -Wall -o $@ $<

t1_calculo_nota: t1_calculo_nota.c
	gcc -Wall -o $@ $<

t1_calculo_nota_int: t1_calculo_nota_int.c
	gcc -Wall -o $@ $<

t1_if: t1_if.c
	gcc -Wall -o $@ $<

t1_while: t1_while.c
	gcc -Wall -o $@ $<

t1_overflow: t1_overflow.c
	gcc -Wall -o $@ $<

.PHONY: clean
clean:
	rm -f t1_hello t1_hello_fail t1_hello_annot
	rm -f t1_tipos_variaveis t1_tamanhos_tipos
	rm -f t1_operadores_int
	rm -f t1_calculo_nota t1_calculo_nota_int
	rm -f t1_if t1_while t1_overflow	
